name: eqx-hamux
channels:
  - conda-forge
  - anaconda
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip>=20.0
  - nb_conda # Assumes jupyter and jupyter_contrib_nbextensions are globally installed