# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/barebones-hamux',
                'doc_host': 'https://bhoov.github.io',
                'git_url': 'https://github.com/bhoov/barebones-hamux',
                'lib_path': 'barebones_hamux'},
  'syms': {}}
